# Generated by Django 3.2 on 2021-08-06 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First', models.CharField(max_length=100)),
                ('Last', models.CharField(max_length=100)),
                ('gender', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True)),
                ('Age', models.IntegerField()),
                ('Disease', models.CharField(max_length=100)),
                ('Doctor', models.CharField(max_length=100)),
                ('fees', models.IntegerField(default=500)),
                ('Started', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
