# Generated by Django 3.2 on 2021-08-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='First',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Last',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Started',
            new_name='MedsStarted',
        ),
    ]
