# Generated by Django 3.2 on 2021-08-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PD', '0003_auto_20210806_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(max_length=3),
        ),
    ]
