# Generated by Django 3.2 on 2021-08-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PD', '0005_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.BooleanField(choices=[('Male', 'Male'), ('Female', 'Female')], default=True),
        ),
    ]
