# Generated by Django 3.2 on 2021-08-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PD', '0007_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.BooleanField(choices=[('Male', 'M'), ('Female', 'F')], default='Male'),
        ),
    ]
